site_name: Dokumentace
site_url: https://docs.histruct.com/


theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  language: en
  features:
    - navigation.tabs
    - navigation.path
    - navigation.indexes

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: white

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: black

# extra:
#   alternate:
#     - name: Česky
#       link: /
#       lang: cs
#     - name: English
#       link: /en/
#       lang: en
# extra:
#   homepage: https://www.histruct.com

markdown_extesion:
  - attr_list
  - md_im_html

nav:

  - "Konfigurátor hal":
    - hbc/index.md

    - "Průvodce návrhem haly":
      - hbc/tutorial/step01.md
      - hbc/tutorial/step02.md
      - hbc/tutorial/step03.md
      - hbc/tutorial/step04.md
      - hbc/tutorial/step05.md
      - hbc/tutorial/step06.md
      - hbc/tutorial/step07.md

    - "Základní konfigurátor":
      - hbc/basic/geometry.md
      - hbc/basic/bays.md
      - hbc/basic/sheeting.md
      - hbc/basic/openings.md
      - hbc/basic/accesories.md
      - hbc/basic/structure.md
      - hbc/basic/outputs.md

    - "Detailní konfigurátor":
      - hbc/advanced/index.md
      - "Rozměry":
        - hbc/advanced/geometry/index.md
        - hbc/advanced/geometry/defaultSettings.md
        - hbc/advanced/geometry/project.md
        - hbc/advanced/geometry/dimension.md
        - hbc/advanced/geometry/leanTo.md
      - "Moduly":
        - hbc/advanced/bays/index.md
        - hbc/advanced/bays/defaultSettings.md
        - hbc/advanced/bays/mainFrames.md
        - hbc/advanced/bays/frameGeometry.md
        - hbc/advanced/bays/portalFrame.md
      - "Opláštění":
        - hbc/advanced/sheeting/index.md
        - hbc/advanced/sheeting/mainSettings.md
        - "Kontextové nastavení opláštění":
          - hbc/advanced/sheeting/context/index.md
          - hbc/advanced/sheeting/context/wall.md
          - hbc/advanced/sheeting/context/wallPart.md
          - hbc/advanced/sheeting/context/wallStrip.md
          - hbc/advanced/sheeting/context/wallSegment.md
          - hbc/advanced/sheeting/context/wallPanel.md
          - hbc/advanced/sheeting/context/roof.md
        - hbc/advanced/sheeting/wallSheeting.md
        - hbc/advanced/sheeting/wallSecondary.md
        - hbc/advanced/sheeting/wallOrientation.md
        - hbc/advanced/sheeting/wallColorSchemeHorizontal.md
        - hbc/advanced/sheeting/wallColorSchemeVertical.md
        - hbc/advanced/sheeting/roofSheeting.md
        - hbc/advanced/sheeting/roofSecondary.md
        - hbc/advanced/sheeting/roofColor.md
        - hbc/advanced/sheeting/roofOverhang.md
      - "Otvory":
        - hbc/advanced/openings/index.md
        - hbc/advanced/openings/colors.md
        - hbc/advanced/openings/ridgeOpenings.md
        - hbc/advanced/openings/roofOpenings.md
        - hbc/advanced/openings/wallOpenings.md
        - "Mapování při změně rozměrů haly": hbc/advanced/openings/mappingAtResizing.md
      - "Doplňky":
        - hbc/advanced/accesories/index.md
        - hbc/advanced/accesories/defaultSettings.md
        - hbc/advanced/accesories/draining.md
        - hbc/advanced/accesories/flashing.md
        - hbc/advanced/accesories/wallAccesories.md
        - "Mapování při změně rozměrů haly": hbc/advanced/openings/mappingAtResizing.md
      - "Konstrukce":
        - hbc/advanced/structure/index.md
      - "Výstupy":
        - hbc/advanced/outputs/index.md

    - "Příběhy":
      - hbc/stories/bathroomStudio.md

  - "CAD":
    - cad/index.md

    - "Střechy":
      - cad/gettingStarted-roofs/Convert3dPdfToObj.md
      - cad/gettingStarted-roofs/ConvertPdfToDxf.md
      - cad/gettingStarted-roofs/CustomisationProject.md
      - cad/gettingStarted-roofs/HiStructForRoofers.md
      - cad/gettingStarted-roofs/ImportDxf.md
      - cad/gettingStarted-roofs/ImportObj.md
      - cad/gettingStarted-roofs/ModellingRoofs.md
      - cad/gettingStarted-roofs/RoofBom.md
      - cad/gettingStarted-roofs/RoofFlashingGenerator.md
      - cad/gettingStarted-roofs/RoofFlashingGutterOptions.md
      - cad/gettingStarted-roofs/RoofFlashingOptions.md
      - cad/gettingStarted-roofs/RoofPolygonGenerator.md
      - cad/gettingStarted-roofs/RoofPolygonTillingDrawing.md
      - cad/gettingStarted-roofs/RoofPolygonTillingOptions.md
      - cad/gettingStarted-roofs/RoofQuote.md

  - "Script": 
    - fcs/index.md

  - "Zpět na HiStruct": https://www.histruct.com


plugins:

  - search:
      lang:
        - cs
        - en

  - i18n:
      docs_structure: folder
      languages:
        - locale: cs
          name: Čeština
          default: true
          build: true

        - locale: en
          name: English
          default: false
          build: true
          site_name: HiStruct Building Configurator - Documentation
          nav_translations:
            "Úvod": "Home"
            "Příběhy": "Stories"
            "Průvodce návrhem haly": "Building design guide"
            "Základní konfigurátor": "Basic configurator"
            "Detailní konfigurátor": "Advanced configurator"
            "Rozměry": "Dimensions"
            "Moduly": "Bays"
            "Opláštění": "Sheeting"
            "Otvory": "Openings"
            "Doplňky": "Accesories"
            "Konstrukce": "Structure"
            "Výstupy": "Outputs"
            "Kontextové nastavení opláštění": "Contextual sheeting settings"
            "Mapování při změně rozměrů haly": "Mapping at resizing"
            "Zpět na HiStruct": "Back to HiStruct"

